export const assessmentSections = [
  { id: "building-information", name: "Building Information" },
  { id: "site-transport", name: "Site and Transport" },
  { id: "water-efficiency", name: "Water Efficiency" },
  { id: "energy-efficiency", name: "Energy Efficiency" },
  { id: "indoor-quality", name: "Indoor Environmental Quality" },
  { id: "materials-resources", name: "Materials & Resources" },
  { id: "waste-pollution", name: "Waste & Pollution" },
  { id: "innovation", name: "Innovation" },
];

export const sectionVariables: Record<string, Array<{ id: string; name: string; maxScore: number; requiresImages?: boolean; requiresVideos?: boolean; requiresLocation?: boolean }>> = {
  "site-transport": [
    { id: "protectRestoreHabitat", name: "Protect or Restore Habitat", maxScore: 6 },
    { id: "heatIslandReduction", name: "Heat Island Reduction", maxScore: 4 },
    { id: "landscapingPlanters", name: "Landscaping and Planters", maxScore: 4, requiresImages: true },
    { id: "publicTransport", name: "Access to Public Transport", maxScore: 4, requiresLocation: true },
    { id: "cyclingWalking", name: "Facilities for Cycling or Walking", maxScore: 3, requiresImages: true },
  ],
  "water-efficiency": [
    { id: "waterQuality", name: "Water Quality", maxScore: 1, requiresImages: true },
    { id: "highEfficiencyFixtures", name: "High Efficiency Water Fixtures", maxScore: 3, requiresVideos: true },
    { id: "rainWaterManagement", name: "Rain Water Management", maxScore: 2, requiresImages: true },
    { id: "outdoorWaterUseReduction", name: "Outdoor Water Use Reduction", maxScore: 2, requiresImages: true },
    { id: "surfaceWaterManagement", name: "Surface Water Run Off/Stormwater Mgt.", maxScore: 1, requiresVideos: true },
    { id: "waterRecycling", name: "Water Recycling", maxScore: 2, requiresVideos: true },
    { id: "meteringLeakDetection", name: "Metering & Leakage Detection System", maxScore: 2, requiresImages: true },
    { id: "waterEfficientIrrigation", name: "Water Efficient Irrigation", maxScore: 2, requiresVideos: true },
    { id: "waterConservationPlan", name: "Water Conservation & Management Plan", maxScore: 1, requiresImages: true },
  ],
  "energy-efficiency": [
    { id: "greenhouseGasEmissionReduction", name: "Greenhouse Gas Emission Reduction", maxScore: 4 },
    { id: "energyEfficientEquipment", name: "Energy Efficient Equipment", maxScore: 4, requiresImages: true },
    { id: "renewableEnergyUse", name: "Renewable Energy Use", maxScore: 4, requiresImages: true },
    { id: "energyMeteringAndMonitoring", name: "Energy Metering And Monitoring", maxScore: 2, requiresImages: true },
    { id: "lowAndZeroCarbonTechnologies", name: "Low And Zero Carbon Technologies", maxScore: 4, requiresImages: true },
    { id: "energyEfficientColdStorage", name: "Energy Efficient Cold Storage", maxScore: 2, requiresImages: true },
    { id: "efficientVentilationAndAcEquipment", name: "Efficient Ventilation And A/C Equipment", maxScore: 2, requiresImages: true },
    { id: "alternativePassiveDesign", name: "Alternative Passive Design", maxScore: 4, requiresVideos: true },
    { id: "embodiedEnergyInBuildingElements", name: "Embodied Energy In Building Elements", maxScore: 3 },
    { id: "ecoFriendlyRefrigerants", name: "Eco-friendly Refrigerants", maxScore: 2, requiresImages: true },
  ],
  "indoor-quality": [
    { id: "daylighting", name: "Daylighting", maxScore: 2 },
    { id: "indoorAirQuality", name: "Indoor Air Quality", maxScore: 1 },
    { id: "naturalLightingSources", name: "Natural Lighting Sources", maxScore: 2 },
    { id: "acousticPerformance", name: "Acoustic Performance", maxScore: 1 },
  ],
  "materials-resources": [
    { id: "recycledContentMaterials", name: "Recycled Content Materials", maxScore: 4 },
    { id: "lowEmbeddedEnergyMaterials", name: "Low Embedded Energy Materials", maxScore: 5 },
    { id: "locallySourcedMaterials", name: "Locally Sourced Materials", maxScore: 7 },
    { id: "thirdPartyCertifiedMaterials", name: "Third-Party Certified Materials", maxScore: 6 },
  ],
  "waste-pollution": [
    { id: "constructionWasteManagement", name: "Construction Waste Management", maxScore: 14 },
    { id: "operationalWasteManagement", name: "Operational Waste Management", maxScore: 1 },
    { id: "pollutionControl", name: "Pollution Control", maxScore: 2 },
  ],
  "innovation": [
    { id: "innovativeTechnologies", name: "Innovative Technologies", maxScore: 11 },
    { id: "sustainableProducts", name: "Sustainable Products", maxScore: 3 },
    { id: "ecoFriendlyDesigns", name: "Eco-Friendly Designs", maxScore: 7 },
  ],
};
